# Generated by Django 4.2.7 on 2023-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('toxicGases', models.FloatField()),
                ('status', models.FloatField()),
                ('eventTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
